<?php

namespace LebedevSoft\AmoCRM;

use LebedevSoft\AmoSync\Console\Commands\AmoSync;
use Illuminate\Support\ServiceProvider;

class AmoServiceProvider extends ServiceProvider
{

    public function boot()
    {
        $this->loadRoutesFrom(__DIR__ . "/../routes/web.php");
        $this->loadMigrationsFrom(__DIR__ . "/../database/migrations");
        $this->publishes([
            __DIR__ . "/../config/amo.php" => config_path("amo.php")
        ]);
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
